# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_vote_candid = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_vote_candid.setGeometry(QtCore.QRect(60, 20, 191, 31))
        self.label_vote_candid.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_vote_candid.setObjectName("label_vote_candid")
        self.radio_vote = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_vote.setGeometry(QtCore.QRect(50, 60, 100, 20))
        self.radio_vote.setObjectName("radio_vote")
        self.radio_exit = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_exit.setGeometry(QtCore.QRect(50, 110, 100, 20))
        self.radio_exit.setObjectName("radio_exit")
        self.push_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_submit.setGeometry(QtCore.QRect(110, 160, 81, 41))
        self.push_submit.setObjectName("push_submit")
        self.label_exit = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_exit.setGeometry(QtCore.QRect(10, 29, 281, 91))
        self.label_exit.setText("")
        self.label_exit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_exit.setObjectName("label_exit")
        self.label_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(40, 200, 231, 20))
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.radio_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_john.setGeometry(QtCore.QRect(50, 60, 100, 20))
        self.radio_john.setObjectName("radio_john")
        self.radio_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_jane.setGeometry(QtCore.QRect(50, 110, 100, 20))
        self.radio_jane.setObjectName("radio_jane")
        self.push_vote = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_vote.setGeometry(QtCore.QRect(100, 160, 121, 41))
        self.push_vote.setObjectName("push_vote")
        self.push_next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_next.setGeometry(QtCore.QRect(90, 90, 121, 41))
        self.push_next.setObjectName("push_next")
        self.label_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(10, 90, 141, 16))
        self.label_id.setObjectName("label_id")
        self.input_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(160, 90, 113, 21))
        self.input_id.setObjectName("input_id")
        self.push_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_enter.setGeometry(QtCore.QRect(90, 120, 121, 41))
        self.push_enter.setObjectName("push_enter")
        self.label_id_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_id_error.setGeometry(QtCore.QRect(20, 160, 261, 61))
        self.label_id_error.setText("")
        self.label_id_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_id_error.setObjectName("label_id_error")
        self.push_end = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_end.setGeometry(QtCore.QRect(90, 210, 131, 41))
        self.push_end.setObjectName("push_end")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_vote_candid.setText(_translate("MainWindow", "VOTER MENU"))
        self.radio_vote.setText(_translate("MainWindow", "Vote"))
        self.radio_exit.setText(_translate("MainWindow", "Exit"))
        self.push_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.radio_john.setText(_translate("MainWindow", "John"))
        self.radio_jane.setText(_translate("MainWindow", "Jane"))
        self.push_vote.setText(_translate("MainWindow", "SUBMIT VOTE"))
        self.push_next.setText(_translate("MainWindow", "Next Voter"))
        self.label_id.setText(_translate("MainWindow", "Enter 4-digit Voter ID:"))
        self.push_enter.setText(_translate("MainWindow", "ENTER"))
        self.push_end.setText(_translate("MainWindow", "End Voting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
